CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK';

SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'TABLE_PK%';

SELECT *
FROM USER_IND_COLUMNS
WHERE TABLE_NAME LIKE 'TABLE_PK%';

CREATE TABLE TABLE_PK2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TABLEPK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TABLEPK2_LOGINPWD_NN NOT NULL,
    TEL VARCHAR2(20)
);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK2';

SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME = 'TABLE_PK2';

INSERT INTO TABLE_PK
    VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
INSERT INTO TABLE_PK
    VALUES('TEST_ID_01', 'PWD02', '010-1234-5678');
    
INSERT INTO TABLE_PK
    VALUES(NULL, 'PWD01', '010-1234-5678');
    
INSERT INTO TABLE_PK(LOGIN_PWD, TEL)
    VALUES('PWD01', '010-1234-5678');
    
CREATE TABLE TABLE_PK3(
    LOGIN_ID VARCHAR2(20),
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TABLEPK3_LOGINPWD_NN NOT NULL,
    TEL VARCHAR2(20),
    CONSTRAINT TABLEPK3_LOGINID_PK PRIMARY KEY(LOGIN_ID)
);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK3';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP', 'DEPT');

INSERT INTO EMP
    VALUES(9999, 'HONG', 'CLERK', 7788, TO_DATE('2017/04/03', 'YYYY/MM/DD'), 1200, NULL, 50);
    
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP_FK', 'DEPT_FK');

INSERT INTO EMP_FK
    VALUES(9999, 'HONG', 'CLERK', 7788, TO_DATE('2017/04/03', 'YYYY/MM/DD'), 1200, NULL, 10);

INSERT INTO DEPT_FK
    VALUES(10, 'TEST_DNAME', 'TEST_LOC');
SELECT * FROM EMP_FK;

DELETE FROM DEPT_FK
WHERE DEPTNO = 10;

ALTER TABLE EMP_FK
ADD CONSTRAINT EMPFK_ENAME_UK UNIQUE(ENAME);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP_FK';

ALTER TABLE EMP_FK
MODIFY(JOB CONSTRAINT EMPFK_JOB_NN NOT NULL);

CREATE TABLE C_TEST1(
    NO NUMBER,
    NAME VARCHAR2(10),
    DEPTNO NUMBER
);

CREATE TABLE C_TEST2(
    NO NUMBER,
    NAME VARCHAR2(10)
);

ALTER TABLE C_TEST1
ADD CONSTRAINT CTEST1_DEPTNO_FK FOREIGN KEY(DEPTNO)
REFERENCES C_TEST2(NO) ON DELETE CASCADE;

ALTER TABLE C_TEST2
ADD CONSTRAINT CTEST2_NO_UK UNIQUE(NO);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('C_TEST1', 'C_TEST2');

INSERT INTO C_TEST2
    VALUES(10, 'AAA');
INSERT INTO C_TEST2
    VALUES(20, 'BBB');
INSERT INTO C_TEST2
    VALUES(30, 'CCC');
SELECT * FROM C_TEST2;
COMMIT;

INSERT INTO C_TEST1
    VALUES(1, 'APPLE', 10);
INSERT INTO C_TEST1
    VALUES(2, 'BANANA', 20);
INSERT INTO C_TEST1
    VALUES(3, 'CHERRY', 30);
SELECT * FROM C_TEST1;
COMMIT;
INSERT INTO C_TEST1
    VALUES(4, 'PEACH', 40);
DELETE FROM C_TEST2
WHERE NO = 10;

ALTER TABLE C_TEST1
DROP CONSTRAINT CTEST1_DEPTNO_FK;

ALTER TABLE C_TEST1
ADD CONSTRAINT CTEST1_DEPTNO_FK FOREIGN KEY(DEPTNO)
REFERENCES C_TEST2(NO)
ON DELETE SET NULL;

DELETE FROM C_TEST2
WHERE NO = 20;
SELECT * FROM C_TEST1;