SELECT SUM(SAL)
FROM EMP;

SELECT MIN(HIREDATE)
FROM EMP;

SELECT COUNT(DISTINCT SAL),
    COUNT(SAL)
FROM EMP
WHERE SAL IS NOT NULL;

SELECT AVG(COMM)
FROM EMP
WHERE DEPTNO = 30;

SELECT AVG(SAL),
    DEPTNO,
    JOB
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO;

SELECT AVG(NVL(COMM,0)), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO,
    JOB,
    AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000;

SELECT DEPTNO,
    JOB,
    AVG(SAL)
FROM EMP
GROUP BY JOB, DEPTNO
HAVING AVG(SAL) >= 500;

SELECT DEPTNO,
    JOB,
    COUNT(*)
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);

SELECT JOB,
    LISTAGG(ENAME, ', ')
    WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES
FROM EMP
GROUP BY JOB;

SELECT JOB, DEPTNO, SAL
FROM EMP;

-- P212 Q1
SELECT DEPTNO,
    TRUNC(AVG(SAL), 0) AS AVG_SAL,
    MAX(SAL) AS MAX_SAL,
    MIN(SAL) AS MIN_SAL,
    COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC
;

-- P212 Q2
SELECT JOB,
    COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3
;

-- P212 Q3
SELECT SUBSTR(HIREDATE, LENGTH(HIREDATE)-1, 2) AS HIRE_YEAR,
    DEPTNO,
    COUNT(*)
FROM EMP
GROUP BY SUBSTR(HIREDATE, LENGTH(HIREDATE)-1, 2), DEPTNO;

-- P213 Q4
SELECT DECODE(COMM, NULL, 'X', 'O') AS EXIST_COMM,
    COUNT(*) AS CNT
FROM EMP
GROUP BY DECODE(COMM, NULL, 'X', 'O')
ORDER BY COUNT(*) DESC;

-- P213 Q5
SELECT DEPTNO,
    TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
    COUNT(*) AS CNT,
    MAX(SAL) AS MAX_SAL,
    SUM(SAL) AS SUM_SAL,
    AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE,'YYYY'))
;

SELECT ename,
    hiredate,
    sal,
    LAG(sal, 0, 99)
    OVER(ORDER BY HIREDATE) AS "LAG"
FROM emp
;
