SELECT t1.empno,
    t1.deptno,
    t2.dname
FROM EMP t1, DEPT t2
WHERE t1.deptno = t2.deptno;

SELECT T1.EMPNO,
    T2.DEPTNO,
    T2.DNAME
FROM EMP T1,DEPT T2;

SELECT CAT_A.NAME,
    CAT_B.NAME,
    CAT_A.NO
FROM CAT_A, CAT_B
WHERE CAT_A.NO = CAT_B.NO;

DESC STUDENT;
DESC PROFESSOR;

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1, PROFESSOR T2
WHERE T1.PROFNO = T2.PROFNO;

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1 JOIN PROFESSOR T2
ON T1.PROFNO = T2.PROFNO;

SELECT  T1.NAME,
    T2.DNAME,
    T3.NAME
FROM STUDENT T1, DEPARTMENT T2, PROFESSOR T3
WHERE T1.DEPTNO1 = T2.DEPTNO AND T1.PROFNO = T3.PROFNO;

DESC STUDENT;
DESC PROFESSOR;

SELECT T1.NAME,
    T1.PROFNO,
    T2.NAME
FROM STUDENT T1, PROFESSOR T2
WHERE DEPTNO1 = 101 AND T1.PROFNO = T2.PROFNO;

DESC CUSTOMER;
DESC GIFT;

SELECT T1.GNAME,
    T2.GNAME
FROM CUSTOMER T1, GIFT T2
WHERE T1.POINT BETWEEN T2.G_START AND T2.G_END;

DESC STUDENT;
DESC SCORE;
DESC HAKJUM;

SELECT T1.NAME,
    T2.TOTAL,
    T3.GRADE
FROM STUDENT T1, SCORE T2, HAKJUM T3
WHERE T1.STUDNO = T2.STUDNO AND (T2.TOTAL BETWEEN T3.MIN_POINT AND T3.MAX_POINT) 
;

SELECT *
FROM SCORE;

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1, PROFESSOR T2
WHERE T1.PROFNO = T2.PROFNO(+);

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1 LEFT OUTER JOIN PROFESSOR T2
ON T1.PROFNO = T2.PROFNO;

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1, PROFESSOR T2
WHERE T1.PROFNO(+) = T2.PROFNO
UNION
SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1, PROFESSOR T2
WHERE T1.PROFNO = T2.PROFNO(+);

SELECT T1.NAME,
    T2.NAME
FROM STUDENT T1 FULL OUTER JOIN PROFESSOR T2
ON T1.PROFNO = T2.PROFNO;

-- P239 Q1
SELECT T2.DEPTNO,
    T2.DNAME,
    T1.EMPNO,
    T1.ENAME,
    T1.SAL
FROM EMP T1, DEPT T2
WHERE T1.DEPTNO = T2.DEPTNO AND T1.SAL > 2000
;

SELECT T2.DEPTNO,
    T2.DNAME,
    T1.EMPNO,
    T1.ENAME,
    T1.SAL
FROM EMP T1 JOIN DEPT T2
ON T1.DEPTNO = T2.DEPTNO AND T1.SAL > 2000;

-- P239 Q2
SELECT T1.DEPTNO,
    T2.DNAME,
    TRUNC(AVG(SAL)),
    MAX(SAL),
    MIN(SAL),
    COUNT(*)
FROM EMP T1, DEPT T2
WHERE T1.DEPTNO = T2.DEPTNO
GROUP BY T1.DEPTNO, T2.DNAME;

SELECT T1.DEPTNO,
    T2.DNAME,
    TRUNC(AVG(SAL)),
    MAX(SAL),
    MIN(SAL),
    COUNT(*)
FROM EMP T1 JOIN DEPT T2
ON T1.DEPTNO = T2.DEPTNO
GROUP BY T1.DEPTNO, T2.DNAME;

-- P239 Q3
SELECT T1.DEPTNO,
    T1.DNAME,
    T2.EMPNO,
    T2.ENAME,
    T2.JOB,
    T2.SAL
FROM DEPT T1, EMP T2
WHERE T1.DEPTNO = T2.DEPTNO(+);

SELECT T1.DEPTNO,
    T1.DNAME,
    T2.EMPNO,
    T2.ENAME,
    T2.JOB,
    T2.SAL
FROM DEPT T1 LEFT OUTER JOIN EMP T2
ON T1.DEPTNO = T2.DEPTNO;

-- P240 Q4
SELECT T1.DEPTNO,
    T1.DNAME,
    T2.EMPNO,
    T2.ENAME,
    T2.MGR,
    T2.SAL,
    T2.DEPTNO,
    T3.LOSAL,
    T3.HISAL,
    T4.EMPNO,
    T4.ENAME
FROM DEPT T1, EMP T2, SALGRADE T3, EMP T4
WHERE T1.DEPTNO = T2.DEPTNO(+)
    AND T2.SAL BETWEEN T3.LOSAL(+) AND T3.HISAL(+)
    AND T2.MGR = T4.EMPNO(+)
ORDER BY T1.DEPTNO
;

SELECT T1.DEPTNO,
    T1.DNAME,
    T2.EMPNO,
    T2.ENAME,
    T2.MGR,
    T2.SAL,
    T2.DEPTNO,
    T3.LOSAL,
    T3.HISAL,
    T4.EMPNO,
    T4.ENAME
FROM DEPT T1 LEFT OUTER JOIN EMP T2 ON T1.DEPTNO = T2.DEPTNO
    LEFT OUTER JOIN SALGRADE T3 ON T2.SAL BETWEEN T3.LOSAL AND T3.HISAL
    LEFT OUTER JOIN EMP T4 ON T2.MGR = T4.EMPNO
ORDER BY T1.DEPTNO;

SELECT *
FROM CUSTOMER;

SELECT *
FROM GIFT;

SELECT *
FROM CUSTOMER T1, GIFT T2
WHERE T1.POINT >= T2.G_START
    AND T2.GNAME = 'Notebook';

SELECT *
FROM PROFESSOR;

SELECT T1.PROFNO,
    T1.NAME,
    TO_CHAR(T1.HIREDATE, 'YYYY/MM/DD'),
    COUNT(T2.HIREDATE)
FROM PROFESSOR T1, PROFESSOR T2
WHERE T1.HIREDATE > T2.HIREDATE(+)
GROUP BY T1.PROFNO, T1.NAME, T1.HIREDATE
ORDER BY COUNT(T2.HIREDATE)
;

SELECT T1.NAME,
    T2.DNAME
FROM STUDENT T1, DEPARTMENT T2
WHERE T1.DEPTNO1 = (
    SELECT DEPTNO1
    FROM STUDENT
    WHERE NAME = 'Anthony Hopkins'
)
AND T1.DEPTNO1 = T2.DEPTNO;

SELECT T1.NAME,
    TO_CHAR(T1.HIREDATE,'YYYY/MM/DD'),
    T2.DNAME
FROM PROFESSOR T1, DEPARTMENT T2
WHERE HIREDATE > (
    SELECT HIREDATE
    FROM PROFESSOR
    WHERE NAME = 'Meg Ryan'
) AND T1.DEPTNO = T2.DEPTNO
;

SELECT T1.NAME,
    T1.WEIGHT
FROM STUDENT T1
WHERE T1.WEIGHT > (
    SELECT AVG(WEIGHT)
    FROM STUDENT
    WHERE DEPTNO1 = 201
);

SELECT *
FROM EMP
WHERE SAL <= (
    SELECT AVG(SAL)
    FROM EMP
) AND DEPTNO = 20;

SELECT MAX(SAL)
FROM EMP;

SELECT T1.NAME,
    T1.POSITION,
    TO_CHAR(T1.PAY,'$999,999,999')
FROM EMP2 T1
WHERE PAY > (
    SELECT MIN(PAY)
    FROM EMP2
    WHERE EMP2.POSITION = 'Section head'
);

SELECT T1.NAME,
    T1.GRADE,
    T1.WEIGHT
FROM STUDENT T1
WHERE T1.WEIGHT < (
    SELECT MIN(WEIGHT)
    FROM STUDENT
    WHERE GRADE = 2
);

SELECT *
FROM DEPT2;

SELECT *
FROM EMP2;

-- P262 Q1
SELECT T1.JOB,
    T1.EMPNO,
    T1.ENAME,
    T1.SAL,
    T2.DEPTNO,
    T2.DNAME
FROM EMP T1, DEPT T2
WHERE T1.JOB = (
    SELECT JOB
    FROM EMP
    WHERE ENAME = 'ALLEN'
) AND T1.DEPTNO = T2.DEPTNO;

-- P262 Q2
SELECT T1.EMPNO,
    T1.ENAME,
    T2.DNAME,
    TO_CHAR(T1.HIREDATE, 'YYYY-MM-DD') AS HIREDATE,
    T2.LOC,
    T1.SAL,
    T3.GRADE
FROM EMP T1, DEPT T2, SALGRADE T3
WHERE T1.SAL > (
    SELECT AVG(SAL)
    FROM EMP
) AND T1.DEPTNO = T2.DEPTNO
AND T1.SAL BETWEEN T3.LOSAL AND T3.HISAL;

-- P263 Q3
SELECT T1.EMPNO,
    T1.ENAME,
    T1.JOB,
    T2.DEPTNO,
    T2.DNAME,
    T2.LOC
FROM EMP T1, DEPT T2
WHERE T1.JOB NOT IN (
    SELECT JOB
    FROM EMP
    WHERE DEPTNO = 30
) AND T1.DEPTNO = T2.DEPTNO AND T1.DEPTNO = 10;

-- P263 Q4
SELECT T1.EMPNO,
    T1.ENAME,
    T1.SAL,
    T2.GRADE
FROM EMP T1, SALGRADE T2
WHERE T1.SAL > (
    SELECT MAX(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN'
) AND T1.SAL BETWEEN T2.LOSAL AND T2.HISAL;

SELECT T1.EMPNO,
    T1.ENAME,
    T1.SAL,
    T2.GRADE
FROM EMP T1, SALGRADE T2
WHERE T1.SAL > ALL (
    SELECT SAL
    FROM EMP
    WHERE JOB = 'SALESMAN'
) AND T1.SAL BETWEEN T2.LOSAL AND T2.HISAL;