SELECT *
FROM EMP;

DROP TABLE DEPT_TEMP;
CREATE TABLE DEPT_TEMP
AS SELECT *
    FROM DEPT;

SELECT * FROM DEPT_TEMP;

COMMIT;

ROLLBACK;

INSERT INTO DEPT_TEMP 
    VALUES(50, 'DATABASE', 'SEOUL');

DELETE DEPT_TEMP
WHERE DEPTNO = 50;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(60, 'IT', 'MOKDONG');

DELETE DEPT_TEMP
WHERE DEPTNO = 60;

-- P287
DROP TABLE CHAP10HW_EMP;
DROP TABLE CHAP10HW_DEPT;
DROP TABLE CHAP10HW_SALGRADE;

CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

-- P287 Q1
INSERT INTO CHAP10HW_DEPT VALUES(50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES(60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES(70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES(80, 'DML', 'BUNDANG');

SELECT * FROM CHAP10HW_DEPT;

-- P287 Q2 노가다여서 PASS

-- P288 Q3
SELECT * FROM CHAP10HW_EMP;

UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE SAL > (
    SELECT AVG(SAL)
    FROM CHAP10HW_EMP
    WHERE DEPTNO = 50
);

-- P288 P4
UPDATE CHAP10HW_EMP
SET DEPTNO = 80, SAL = SAL * 1.1
WHERE HIREDATE > (
    SELECT MIN(HIREDATE)
    FROM CHAP10HW_EMP
    WHERE DEPTNO = 60
);

-- P289 P5
DELETE FROM CHAP10HW_EMP
WHERE EMPNO IN (
    SELECT EMPNO
    FROM CHAP10HW_EMP T1, CHAP10HW_SALGRADE T2
    WHERE T1.SAL BETWEEN T2.LOSAL AND T2.HISAL
    AND T2.GRADE = 5
);