SELECT * FROM EMP;

-- P324 Q1
DROP TABLE EMP_HW;
CREATE TABLE EMP_HW
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2)
);
DESC EMP_HW;

-- P324 Q2
ALTER TABLE EMP_HW
ADD(BIGO VARCHAR2(20));

DESC EMP_HW;

-- P324 Q3
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);
DESC EMP_HW;

-- P324 Q4
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;

DESC EMP_HW;

-- P325 Q5
INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
(
    SELECT *
    FROM EMP
);

SELECT * FROM EMP_HW;

-- P325 Q5
DROP TABLE EMP_HW;